# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# commented main to avoid unnecessary for sample project runs
trigger:
  - some
  # - main

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRMPipeline-conn'
    subscriptionId: '805e4ea6-018f-42e9-b0a5-48d6efcec787'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-AzureRMPipeline'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/TsarSPb/AzureRMPipeline/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName azurermpipe'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'